version: '3.1'
volumes:
  content:
services:

  ghost:
    image: ghost:3-alpine
    restart: always
    ports:
      - 8080:2368
    volumes:
      - content:/var/lib/ghost/content
      # - ./config.production.json:/var/lib/ghost/config.production.json
    environment:
      url: http://localhost:8080
